#
# Copyright (c) 2017 Shenshu Technologies Co., Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-$(CONFIG_VENDOR_COMMON)	+= init_regs.o uart.o soc.o util.o
extra-$(CONFIG_MCI)	+= mci_boot.o
obj-y	+= dummy.o


